// ============================================================
// questions.js — 100 questions per language × 3 languages
// Easy: ~33 | Medium: ~33 | Hard: ~34
// The game picks 8 random questions each round
// ============================================================

const QUESTIONS = {
  en: {
    easy: [
      { q: "Which country won the 2022 FIFA World Cup?", options: ["France","Brazil","Argentina","Germany"], answer: 2 },
      { q: "How many players are on a football team on the pitch?", options: ["9","10","11","12"], answer: 2 },
      { q: "Which club is known as 'The Red Devils'?", options: ["Arsenal","Liverpool","Manchester United","AC Milan"], answer: 2 },
      { q: "Who is the all-time top scorer in World Cup history?", options: ["Pelé","Miroslav Klose","Ronaldo (Brazil)","Just Fontaine"], answer: 1 },
      { q: "In which country is the Santiago Bernabéu stadium?", options: ["Portugal","Argentina","Spain","Italy"], answer: 2 },
      { q: "Which player is nicknamed 'CR7'?", options: ["Ronaldinho","Cristiano Ronaldo","Carlos Roa","Carlos Valderrama"], answer: 1 },
      { q: "How long is a standard football match?", options: ["80 min","85 min","90 min","95 min"], answer: 2 },
      { q: "Which country has won the most FIFA World Cup titles?", options: ["Germany","Argentina","Italy","Brazil"], answer: 3 },
      { q: "What shape is a football pitch?", options: ["Square","Circle","Rectangle","Triangle"], answer: 2 },
      { q: "Which country does Kylian Mbappé play for?", options: ["Belgium","Portugal","France","Spain"], answer: 2 },
      { q: "What colors are the referee's cards?", options: ["Red and Blue","Yellow and Red","Green and Yellow","Orange and Red"], answer: 1 },
      { q: "Which country does Lionel Messi play for?", options: ["Brazil","Uruguay","Chile","Argentina"], answer: 3 },
      { q: "What is a 'hat-trick' in football?", options: ["3 goals by one player","3 assists","3 yellow cards","3 saves"], answer: 0 },
      { q: "What is the name of the Real Madrid vs Barcelona derby?", options: ["Derby de Madrid","El Clásico","Catalan Derby","La Manita"], answer: 1 },
      { q: "Which team won the first FIFA World Cup in 1930?", options: ["Brazil","Argentina","Uruguay","Italy"], answer: 2 },
      { q: "How many substitutes can sit on the bench?", options: ["5","7","9","11"], answer: 1 },
      { q: "Which club plays at Old Trafford?", options: ["Liverpool","Chelsea","Manchester United","Arsenal"], answer: 2 },
      { q: "What is the name of the trophy given to the FIFA World Cup winner?", options: ["The Golden Cup","Jules Rimet Trophy","FIFA Trophy","World Trophy"], answer: 1 },
      { q: "Which country won the 2018 FIFA World Cup?", options: ["Germany","Croatia","Belgium","France"], answer: 3 },
      { q: "How many minutes is each half of a football match?", options: ["40","45","50","60"], answer: 1 },
      { q: "Which city does FC Barcelona come from?", options: ["Madrid","Seville","Barcelona","Valencia"], answer: 2 },
      { q: "What color jersey does Brazil's national team traditionally wear?", options: ["Green","Blue","Yellow","White"], answer: 2 },
      { q: "Which club is known as 'The Blues' in London?", options: ["Arsenal","Tottenham","Chelsea","West Ham"], answer: 2 },
      { q: "Who won the 2014 FIFA World Cup?", options: ["Brazil","Argentina","Germany","France"], answer: 2 },
      { q: "Which player is known as 'The Flea'?", options: ["Neymar","Messi","Ronaldo","Mbappé"], answer: 1 },
      { q: "In football, what does a red card mean?", options: ["Warning","Free kick","Player is sent off","Penalty"], answer: 2 },
      { q: "Which country does Neymar play for?", options: ["Argentina","Colombia","Brazil","Portugal"], answer: 2 },
      { q: "What is the maximum number of players in a squad for a World Cup?", options: ["23","25","26","30"], answer: 2 },
      { q: "Which club is nicknamed 'The Reds' in Liverpool?", options: ["Everton","Liverpool","Manchester United","Arsenal"], answer: 1 },
      { q: "How many times can a goalkeeper handle the ball outside the box?", options: ["Once","Twice","Never","Unlimited"], answer: 2 },
      { q: "Who hosts the UEFA Champions League final venue each year?", options: ["FIFA","UEFA","Host nation FA","IOC"], answer: 1 },
      { q: "Which country won Euro 2020 (played in 2021)?", options: ["England","France","Portugal","Italy"], answer: 3 },
      { q: "What is the diameter of a standard football goal in meters?", options: ["5.5 m","6 m","7.32 m","8 m"], answer: 2 },
    ],
    medium: [
      { q: "Which club did Messi join after leaving Barcelona in 2021?", options: ["Juventus","PSG","Manchester City","Bayern Munich"], answer: 1 },
      { q: "What year was FIFA founded?", options: ["1900","1904","1910","1920"], answer: 1 },
      { q: "Which nation hosted the 2018 FIFA World Cup?", options: ["Brazil","Germany","Russia","France"], answer: 2 },
      { q: "Who won the Ballon d'Or in 2023?", options: ["Kylian Mbappé","Erling Haaland","Lionel Messi","Karim Benzema"], answer: 2 },
      { q: "Which club has the most UEFA Champions League titles?", options: ["Barcelona","Bayern Munich","Real Madrid","AC Milan"], answer: 2 },
      { q: "Maximum substitutions allowed in a standard match?", options: ["3","4","5","6"], answer: 2 },
      { q: "Who scored the 'Hand of God' goal in 1986?", options: ["Pelé","Diego Maradona","Michel Platini","Gary Lineker"], answer: 1 },
      { q: "Which English club is nicknamed 'The Gunners'?", options: ["Chelsea","Tottenham","Arsenal","West Ham"], answer: 2 },
      { q: "Who won the 2021-22 UEFA Champions League?", options: ["Liverpool","Manchester City","Chelsea","Real Madrid"], answer: 3 },
      { q: "In which country was Cristiano Ronaldo born?", options: ["Spain","Brazil","Portugal","Italy"], answer: 2 },
      { q: "Which club is known as 'The Old Lady'?", options: ["AC Milan","Inter Milan","Juventus","Lazio"], answer: 2 },
      { q: "How many times has France won the FIFA World Cup?", options: ["1","2","3","4"], answer: 1 },
      { q: "Who is the all-time top scorer for Real Madrid?", options: ["Raúl","Benzema","Ronaldo","Zidane"], answer: 2 },
      { q: "Which stadium is home to FC Barcelona?", options: ["Wanda Metropolitano","Camp Nou","Bernabéu","San Siro"], answer: 1 },
      { q: "Which African country reached the 2022 World Cup semi-finals?", options: ["Nigeria","Senegal","Morocco","Cameroon"], answer: 2 },
      { q: "Who was the top scorer at the 2018 FIFA World Cup?", options: ["Messi","Ronaldo","Harry Kane","Lukaku"], answer: 2 },
      { q: "Which club did Neymar join after Barcelona in 2017?", options: ["Real Madrid","Manchester City","PSG","Bayern Munich"], answer: 2 },
      { q: "Which country won the Copa América 2021?", options: ["Brazil","Colombia","Uruguay","Argentina"], answer: 3 },
      { q: "Who won the Premier League in 2022-23?", options: ["Liverpool","Manchester City","Arsenal","Chelsea"], answer: 1 },
      { q: "Which Italian club plays at San Siro alongside Inter Milan?", options: ["Juventus","Lazio","AC Milan","Roma"], answer: 2 },
      { q: "Which player scored the most Premier League goals ever?", options: ["Wayne Rooney","Andrew Cole","Alan Shearer","Frank Lampard"], answer: 2 },
      { q: "What nationality is Robert Lewandowski?", options: ["Czech","Slovak","Hungarian","Polish"], answer: 3 },
      { q: "Which club won the treble in 1999 under Sir Alex Ferguson?", options: ["Arsenal","Chelsea","Manchester United","Liverpool"], answer: 2 },
      { q: "Who is the most capped player in the history of the England national team?", options: ["David Beckham","Wayne Rooney","Steven Gerrard","Peter Shilton"], answer: 1 },
      { q: "Which club plays at the Allianz Arena?", options: ["Borussia Dortmund","Bayern Munich","Bayer Leverkusen","Schalke"], answer: 1 },
      { q: "Which country won the 2016 UEFA European Championship?", options: ["France","Germany","Wales","Portugal"], answer: 3 },
      { q: "In which year did Zinedine Zidane famously headbutt Marco Materazzi?", options: ["2002","2004","2006","2008"], answer: 2 },
      { q: "Which player won the Golden Ball at the 2022 World Cup?", options: ["Mbappé","Modric","Messi","Benzema"], answer: 2 },
      { q: "Which club did Erling Haaland join in 2022?", options: ["PSG","Real Madrid","Manchester City","Barcelona"], answer: 2 },
      { q: "Who manages the England national team as of 2024?", options: ["Gareth Southgate","Thomas Tuchel","Pep Guardiola","Eddie Howe"], answer: 1 },
      { q: "Which country does Virgil van Dijk represent?", options: ["Belgium","Denmark","Netherlands","Germany"], answer: 2 },
      { q: "Which South American club has the most Copa Libertadores titles?", options: ["Boca Juniors","River Plate","Santos","Independiente"], answer: 3 },
      { q: "In what year did Leicester City famously win the Premier League?", options: ["2014","2015","2016","2017"], answer: 2 },
    ],
    hard: [
      { q: "Which keeper holds the PL record for most clean sheets?", options: ["Schmeichel","David Seaman","Petr Čech","Van der Sar"], answer: 2 },
      { q: "What year did Ajax win their last Champions League?", options: ["1992","1995","1997","1999"], answer: 1 },
      { q: "Who scored France's winner in the 1998 WC final?", options: ["Zidane","Thierry Henry","Emmanuel Petit","Trezeguet"], answer: 0 },
      { q: "Who has won the most Ballon d'Or awards as of 2024?", options: ["Cristiano Ronaldo","Lionel Messi","Ronaldinho","Michel Platini"], answer: 1 },
      { q: "What nationality is legendary keeper Lev Yashin?", options: ["Ukrainian","German","Soviet/Russian","Hungarian"], answer: 2 },
      { q: "Which club did Zidane leave to join Real Madrid?", options: ["Marseille","Monaco","Juventus","Lyon"], answer: 2 },
      { q: "How many times has Brazil won the FIFA World Cup?", options: ["4","5","6","3"], answer: 1 },
      { q: "Who was the Golden Boot winner at the 2014 World Cup?", options: ["Messi","Neymar","Thomas Müller","James Rodríguez"], answer: 2 },
      { q: "Which player holds the record for most international goals as of 2024?", options: ["Ronaldo","Messi","Ali Daei","Mokhtar Dahari"], answer: 0 },
      { q: "In which year was the offside rule significantly changed?", options: ["1863","1883","1925","1950"], answer: 2 },
      { q: "Who scored the fastest hat-trick in Premier League history?", options: ["Robbie Fowler","Michael Owen","Sadio Mané","Alan Shearer"], answer: 0 },
      { q: "Which club has won the most Argentine Primera División titles?", options: ["Boca Juniors","San Lorenzo","River Plate","Racing Club"], answer: 2 },
      { q: "Which country won the first UEFA European Championship in 1960?", options: ["Spain","Italy","Soviet Union","Yugoslavia"], answer: 2 },
      { q: "How many clubs has CR7 played for as of 2024?", options: ["4","5","6","7"], answer: 1 },
      { q: "Which player is known as 'The Divine Ponytail'?", options: ["Francesco Totti","Roberto Baggio","Alessandro Del Piero","Gianfranco Zola"], answer: 1 },
      { q: "What is Pelé's real first name?", options: ["Eduardo","Edson","Ernesto","Evaristo"], answer: 1 },
      { q: "Which club did Ronaldo (R9) play for before Real Madrid?", options: ["Ajax","PSV","Barcelona","Cruzeiro"], answer: 1 },
      { q: "Who was the first player to win the World Cup three times?", options: ["Garrincha","Pelé","Didí","Nilton Santos"], answer: 1 },
      { q: "Which country did Diego Maradona lead to the 1986 World Cup title?", options: ["Uruguay","Brazil","Argentina","Italy"], answer: 2 },
      { q: "Which club did Thierry Henry play for before Arsenal?", options: ["Monaco","PSG","Juventus","Lyon"], answer: 0 },
      { q: "Who holds the record for most appearances in the UEFA Champions League?", options: ["Xavi","Casillas","Cristiano Ronaldo","Raúl"], answer: 2 },
      { q: "Which player has scored the most goals in a single Premier League season?", options: ["Alan Shearer","Andrew Cole","Mohamed Salah","Erling Haaland"], answer: 3 },
      { q: "In which year did the Premier League introduce VAR?", options: ["2017","2018","2019","2020"], answer: 2 },
      { q: "Which club did Luis Suárez join after leaving Liverpool?", options: ["Real Madrid","PSG","Barcelona","Juventus"], answer: 2 },
      { q: "How many African nations have reached the semi-finals of a World Cup?", options: ["0","1","2","3"], answer: 2 },
      { q: "Who was the first non-European/South American player to win the Ballon d'Or?", options: ["George Weah","Samuel Eto'o","Didier Drogba","Jay-Jay Okocha"], answer: 0 },
      { q: "Which referee sent off Zinedine Zidane in the 2006 World Cup final?", options: ["Pierluigi Collina","Horacio Elizondo","Graham Poll","Howard Webb"], answer: 1 },
      { q: "Which club won the inaugural UEFA Champions League in 1956?", options: ["AC Milan","Barcelona","Real Madrid","Juventus"], answer: 2 },
      { q: "What was the score when Germany beat Brazil 7-1 in the 2014 World Cup?", options: ["6-0","7-1","5-0","8-2"], answer: 1 },
      { q: "Who was the manager of France's 1998 World Cup winning team?", options: ["Didier Deschamps","Arsène Wenger","Aimé Jacquet","Roger Lemerre"], answer: 2 },
      { q: "Which country has hosted the FIFA World Cup the most times?", options: ["Brazil","Germany","Italy","Mexico"], answer: 3 },
      { q: "What position did Franz Beckenbauer famously play?", options: ["Striker","Winger","Sweeper/Libero","Goalkeeper"], answer: 2 },
      { q: "Who scored the only goal in the 2010 World Cup final?", options: ["David Villa","Xavi","Andrés Iniesta","Fernando Torres"], answer: 2 },
      { q: "Which club has won the most La Liga titles?", options: ["Barcelona","Atletico Madrid","Valencia","Real Madrid"], answer: 3 },
    ]
  },

  fr: {
    easy: [
      { q: "Quel pays a remporté la Coupe du Monde 2022 ?", options: ["France","Brésil","Argentine","Allemagne"], answer: 2 },
      { q: "Combien de joueurs sur le terrain par équipe ?", options: ["9","10","11","12"], answer: 2 },
      { q: "Quel club est surnommé 'Les Diables Rouges' ?", options: ["Arsenal","Liverpool","Manchester United","AC Milan"], answer: 2 },
      { q: "Meilleur buteur de l'histoire de la Coupe du Monde ?", options: ["Pelé","Miroslav Klose","Ronaldo (Brésil)","Just Fontaine"], answer: 1 },
      { q: "Dans quel pays se trouve le Bernabéu ?", options: ["Portugal","Argentine","Espagne","Italie"], answer: 2 },
      { q: "Quel joueur est surnommé 'CR7' ?", options: ["Ronaldinho","Cristiano Ronaldo","Carlos Roa","Valderrama"], answer: 1 },
      { q: "Durée normale d'un match de football ?", options: ["80 min","85 min","90 min","95 min"], answer: 2 },
      { q: "Quel pays a le plus de Coupes du Monde ?", options: ["Allemagne","Argentine","Italie","Brésil"], answer: 3 },
      { q: "Quelle forme a un terrain de football ?", options: ["Carré","Cercle","Rectangle","Triangle"], answer: 2 },
      { q: "Pour quelle sélection joue Kylian Mbappé ?", options: ["Belgique","Portugal","France","Espagne"], answer: 2 },
      { q: "Quelles couleurs ont les cartons de l'arbitre ?", options: ["Rouge et bleu","Jaune et rouge","Vert et jaune","Orange et rouge"], answer: 1 },
      { q: "Pour quel pays joue Lionel Messi ?", options: ["Brésil","Uruguay","Chili","Argentine"], answer: 3 },
      { q: "Qu'est-ce qu'un 'hat-trick' ?", options: ["3 buts par un joueur","3 passes décisives","3 cartons jaunes","3 arrêts"], answer: 0 },
      { q: "Comment s'appelle le derby Real Madrid - Barcelone ?", options: ["Derby de Madrid","El Clásico","Derby Catalan","La Manita"], answer: 1 },
      { q: "Quelle équipe a gagné la première Coupe du Monde en 1930 ?", options: ["Brésil","Argentine","Uruguay","Italie"], answer: 2 },
      { q: "Combien de remplaçants peuvent être sur le banc ?", options: ["5","7","9","11"], answer: 1 },
      { q: "Quel club joue à Old Trafford ?", options: ["Liverpool","Chelsea","Manchester United","Arsenal"], answer: 2 },
      { q: "Quel pays a remporté la Coupe du Monde 2018 ?", options: ["Allemagne","Croatie","Belgique","France"], answer: 3 },
      { q: "Combien de minutes dure chaque mi-temps ?", options: ["40","45","50","60"], answer: 1 },
      { q: "Dans quelle ville joue le FC Barcelone ?", options: ["Madrid","Séville","Barcelone","Valence"], answer: 2 },
      { q: "De quelle couleur est le maillot traditionnel du Brésil ?", options: ["Vert","Bleu","Jaune","Blanc"], answer: 2 },
      { q: "Quel club londonien est surnommé 'The Blues' ?", options: ["Arsenal","Tottenham","Chelsea","West Ham"], answer: 2 },
      { q: "Qui a gagné la Coupe du Monde 2014 ?", options: ["Brésil","Argentine","Allemagne","France"], answer: 2 },
      { q: "Quel joueur est surnommé 'La Pulga' (La Puce) ?", options: ["Neymar","Messi","Ronaldo","Mbappé"], answer: 1 },
      { q: "Que signifie un carton rouge en football ?", options: ["Avertissement","Coup franc","Expulsion","Penalty"], answer: 2 },
      { q: "Pour quel pays joue Neymar ?", options: ["Argentine","Colombie","Brésil","Portugal"], answer: 2 },
      { q: "Quel club est surnommé 'Les Reds' à Liverpool ?", options: ["Everton","Liverpool","Manchester United","Arsenal"], answer: 1 },
      { q: "Qui a remporté l'Euro 2020 (joué en 2021) ?", options: ["Angleterre","France","Portugal","Italie"], answer: 3 },
      { q: "Quelle est la largeur d'un but de football ?", options: ["5,5 m","6 m","7,32 m","8 m"], answer: 2 },
      { q: "Quel club est surnommé 'Les Citoyens' ?", options: ["Chelsea","Arsenal","Manchester City","Tottenham"], answer: 2 },
      { q: "Dans quelle ville se trouve le stade du Parc des Princes ?", options: ["Lyon","Marseille","Paris","Bordeaux"], answer: 2 },
      { q: "Quelle équipe a remporté la Ligue des Champions 2022-23 ?", options: ["Liverpool","Bayern Munich","PSG","Manchester City"], answer: 3 },
      { q: "Combien de buts Kylian Mbappé a-t-il marqués au Mondial 2022 ?", options: ["6","7","8","9"], answer: 1 },
    ],
    medium: [
      { q: "Quel club Messi a-t-il rejoint après Barcelone en 2021 ?", options: ["Juventus","PSG","Man City","Bayern"], answer: 1 },
      { q: "En quelle année la FIFA a-t-elle été fondée ?", options: ["1900","1904","1910","1920"], answer: 1 },
      { q: "Quelle nation a organisé la Coupe du Monde 2018 ?", options: ["Brésil","Allemagne","Russie","France"], answer: 2 },
      { q: "Qui a gagné le Ballon d'Or 2023 ?", options: ["Mbappé","Haaland","Messi","Benzema"], answer: 2 },
      { q: "Club avec le plus de titres en Ligue des Champions ?", options: ["Barcelone","Bayern","Real Madrid","AC Milan"], answer: 2 },
      { q: "Nombre max de remplaçants autorisés en match officiel ?", options: ["3","4","5","6"], answer: 2 },
      { q: "Qui a marqué le but 'Main de Dieu' en 1986 ?", options: ["Pelé","Maradona","Platini","Lineker"], answer: 1 },
      { q: "Quel club anglais est surnommé 'The Gunners' ?", options: ["Chelsea","Tottenham","Arsenal","West Ham"], answer: 2 },
      { q: "Qui a remporté la Ligue des Champions 2021-22 ?", options: ["Liverpool","Man City","Chelsea","Real Madrid"], answer: 3 },
      { q: "Dans quel pays est né Cristiano Ronaldo ?", options: ["Espagne","Brésil","Portugal","Italie"], answer: 2 },
      { q: "Quel club est surnommé 'La Vieille Dame' ?", options: ["AC Milan","Inter Milan","Juventus","Lazio"], answer: 2 },
      { q: "Combien de fois la France a-t-elle remporté la Coupe du Monde ?", options: ["1","2","3","4"], answer: 1 },
      { q: "Qui est le meilleur buteur historique du Real Madrid ?", options: ["Raúl","Benzema","Ronaldo","Zidane"], answer: 2 },
      { q: "Quel est le stade du FC Barcelone ?", options: ["Wanda Metropolitano","Camp Nou","Bernabéu","San Siro"], answer: 1 },
      { q: "Quel pays africain a atteint les demi-finales du Mondial 2022 ?", options: ["Nigeria","Sénégal","Maroc","Cameroun"], answer: 2 },
      { q: "Qui était le meilleur buteur du Mondial 2018 ?", options: ["Messi","Ronaldo","Harry Kane","Lukaku"], answer: 2 },
      { q: "Quel club Neymar a-t-il rejoint après Barcelone en 2017 ?", options: ["Real Madrid","Man City","PSG","Bayern Munich"], answer: 2 },
      { q: "Quel pays a remporté la Copa América 2021 ?", options: ["Brésil","Colombie","Uruguay","Argentine"], answer: 3 },
      { q: "Qui a remporté la Premier League en 2022-23 ?", options: ["Liverpool","Manchester City","Arsenal","Chelsea"], answer: 1 },
      { q: "Quel club italien partage San Siro avec l'Inter Milan ?", options: ["Juventus","Lazio","AC Milan","Roma"], answer: 2 },
      { q: "Qui détient le record de buts en Premier League ?", options: ["Wayne Rooney","Andrew Cole","Alan Shearer","Frank Lampard"], answer: 2 },
      { q: "Quelle est la nationalité de Robert Lewandowski ?", options: ["Tchèque","Slovaque","Hongroise","Polonaise"], answer: 3 },
      { q: "Quel club a réalisé le triplé en 1999 sous Sir Alex Ferguson ?", options: ["Arsenal","Chelsea","Manchester United","Liverpool"], answer: 2 },
      { q: "Qui est le joueur le plus capé de l'équipe d'Angleterre ?", options: ["Beckham","Wayne Rooney","Gerrard","Peter Shilton"], answer: 1 },
      { q: "Quel club joue à l'Allianz Arena ?", options: ["Borussia Dortmund","Bayern Munich","Bayer Leverkusen","Schalke"], answer: 1 },
      { q: "Quel pays a remporté l'Euro 2016 ?", options: ["France","Allemagne","Pays de Galles","Portugal"], answer: 3 },
      { q: "En quelle année Zidane a-t-il donné son coup de tête à Materazzi ?", options: ["2002","2004","2006","2008"], answer: 2 },
      { q: "Qui a remporté le Ballon d'Or du Mondial 2022 ?", options: ["Mbappé","Modric","Messi","Benzema"], answer: 2 },
      { q: "Quel club Haaland a-t-il rejoint en 2022 ?", options: ["PSG","Real Madrid","Manchester City","Barcelone"], answer: 2 },
      { q: "Quel pays Virgil van Dijk représente-t-il ?", options: ["Belgique","Danemark","Pays-Bas","Allemagne"], answer: 2 },
      { q: "En quelle année Leicester City a-t-il remporté la Premier League ?", options: ["2014","2015","2016","2017"], answer: 2 },
      { q: "Quel club sud-américain a le plus de Copa Libertadores ?", options: ["Boca Juniors","River Plate","Santos","Independiente"], answer: 3 },
      { q: "Quel joueur a marqué le but décisif en finale de l'Euro 2016 ?", options: ["Cristiano Ronaldo","Nani","Eder","Ricardo Quaresma"], answer: 2 },
    ],
    hard: [
      { q: "Gardien avec le record de clean sheets en Premier League ?", options: ["Schmeichel","Seaman","Petr Čech","Van der Sar"], answer: 2 },
      { q: "Année du dernier titre de l'Ajax en C1 ?", options: ["1992","1995","1997","1999"], answer: 1 },
      { q: "Qui a marqué le but vainqueur de la France en finale 1998 ?", options: ["Zidane","Henry","Petit","Trezeguet"], answer: 0 },
      { q: "Joueur avec le plus de Ballons d'Or en 2024 ?", options: ["Ronaldo","Messi","Ronaldinho","Platini"], answer: 1 },
      { q: "Nationalité du légendaire gardien Lev Yachine ?", options: ["Ukrainienne","Allemande","Soviétique/Russe","Hongroise"], answer: 2 },
      { q: "Quel club Zidane a-t-il quitté pour le Real Madrid ?", options: ["Marseille","Monaco","Juventus","Lyon"], answer: 2 },
      { q: "Combien de fois le Brésil a-t-il remporté la Coupe du Monde ?", options: ["4","5","6","3"], answer: 1 },
      { q: "Meilleur buteur du Mondial 2014 ?", options: ["Messi","Neymar","T. Müller","James"], answer: 2 },
      { q: "Quel joueur détient le record de buts internationaux en 2024 ?", options: ["Ronaldo","Messi","Ali Daei","Mokhtar Dahari"], answer: 0 },
      { q: "En quelle année la règle du hors-jeu a-t-elle été modifiée ?", options: ["1863","1883","1925","1950"], answer: 2 },
      { q: "Qui a marqué le hat-trick le plus rapide en Premier League ?", options: ["Robbie Fowler","Michael Owen","Sadio Mané","Alan Shearer"], answer: 0 },
      { q: "Quel club a le plus de titres en Primera División argentine ?", options: ["Boca Juniors","San Lorenzo","River Plate","Racing Club"], answer: 2 },
      { q: "Quel pays a remporté le premier Euro UEFA en 1960 ?", options: ["Espagne","Italie","Union Soviétique","Yougoslavie"], answer: 2 },
      { q: "Pour combien de clubs CR7 a-t-il joué en 2024 ?", options: ["4","5","6","7"], answer: 1 },
      { q: "Quel joueur est surnommé 'La Queue de Cheval Divine' ?", options: ["Totti","Roberto Baggio","Del Piero","Zola"], answer: 1 },
      { q: "Quel est le vrai prénom de Pelé ?", options: ["Eduardo","Edson","Ernesto","Evaristo"], answer: 1 },
      { q: "Quel club Ronaldo (R9) a-t-il quitté avant le Real Madrid ?", options: ["Ajax","PSV","Barcelone","Cruzeiro"], answer: 1 },
      { q: "Qui a été le premier joueur à remporter 3 fois la Coupe du Monde ?", options: ["Garrincha","Pelé","Didí","Nilton Santos"], answer: 1 },
      { q: "Quel club Thierry Henry a-t-il quitté avant Arsenal ?", options: ["Monaco","PSG","Juventus","Lyon"], answer: 0 },
      { q: "Qui détient le record d'apparitions en Ligue des Champions ?", options: ["Xavi","Casillas","Cristiano Ronaldo","Raúl"], answer: 2 },
      { q: "Quel joueur a inscrit le plus de buts sur une saison de PL ?", options: ["Shearer","Andrew Cole","Mohamed Salah","Erling Haaland"], answer: 3 },
      { q: "En quelle année la VAR a-t-elle été introduite en Premier League ?", options: ["2017","2018","2019","2020"], answer: 2 },
      { q: "Quel club Luis Suárez a-t-il rejoint après Liverpool ?", options: ["Real Madrid","PSG","Barcelone","Juventus"], answer: 2 },
      { q: "Combien de pays africains ont atteint les demi-finales d'un Mondial ?", options: ["0","1","2","3"], answer: 2 },
      { q: "Quel fut le premier non-Européen/Sud-Américain à remporter le Ballon d'Or ?", options: ["George Weah","Samuel Eto'o","Didier Drogba","Jay-Jay Okocha"], answer: 0 },
      { q: "Quel arbitre a expulsé Zidane en finale du Mondial 2006 ?", options: ["Pierluigi Collina","Horacio Elizondo","Graham Poll","Howard Webb"], answer: 1 },
      { q: "Quel club a remporté la première Ligue des Champions en 1956 ?", options: ["AC Milan","Barcelone","Real Madrid","Juventus"], answer: 2 },
      { q: "Quel était le score du 7-1 Allemagne - Brésil en 2014 ?", options: ["6-0","7-1","5-0","8-2"], answer: 1 },
      { q: "Qui était le sélectionneur de la France lors du Mondial 1998 ?", options: ["Deschamps","Arsène Wenger","Aimé Jacquet","Roger Lemerre"], answer: 2 },
      { q: "Quel pays a accueilli le plus de Coupes du Monde ?", options: ["Brésil","Allemagne","Italie","Mexique"], answer: 3 },
      { q: "Quel poste occupait Franz Beckenbauer ?", options: ["Attaquant","Ailier","Libero/Sweeper","Gardien"], answer: 2 },
      { q: "Qui a marqué l'unique but de la finale du Mondial 2010 ?", options: ["David Villa","Xavi","Andrés Iniesta","Fernando Torres"], answer: 2 },
      { q: "Quel club a remporté le plus de titres en Liga espagnole ?", options: ["Barcelone","Atlético Madrid","Valence","Real Madrid"], answer: 3 },
      { q: "En quelle année Ronaldinho a-t-il remporté le Ballon d'Or ?", options: ["2003","2004","2005","2006"], answer: 2 },
    ]
  },

  ar: {
    easy: [
      { q: "أي منتخب فاز بكأس العالم 2022؟", options: ["فرنسا","البرازيل","الأرجنتين","ألمانيا"], answer: 2 },
      { q: "كم عدد لاعبي فريق كرة القدم في الملعب؟", options: ["9","10","11","12"], answer: 2 },
      { q: "أي نادٍ يُعرف بـ'الشياطين الحمر'؟", options: ["أرسنال","ليفربول","مانشستر يونايتد","ميلان"], answer: 2 },
      { q: "من هو الهداف التاريخي في كأس العالم؟", options: ["بيليه","كلوزي","رونالدو","فونتين"], answer: 1 },
      { q: "في أي بلد يقع ملعب سانتياغو برنابيو؟", options: ["البرتغال","الأرجنتين","إسبانيا","إيطاليا"], answer: 2 },
      { q: "أي لاعب يُلقّب بـ CR7؟", options: ["رونالدينيو","كريستيانو رونالدو","رواه","فالديراما"], answer: 1 },
      { q: "ما مدة مباراة كرة القدم الرسمية؟", options: ["80 دقيقة","85 دقيقة","90 دقيقة","95 دقيقة"], answer: 2 },
      { q: "أي دولة فازت بأكبر عدد من كؤوس العالم؟", options: ["ألمانيا","الأرجنتين","إيطاليا","البرازيل"], answer: 3 },
      { q: "ما شكل أرضية ملعب كرة القدم؟", options: ["مربع","دائرة","مستطيل","مثلث"], answer: 2 },
      { q: "ما منتخب كيليان مبابي؟", options: ["بلجيكا","البرتغال","فرنسا","إسبانيا"], answer: 2 },
      { q: "ما ألوان بطاقات الحكم في كرة القدم؟", options: ["أحمر وأزرق","أصفر وأحمر","أخضر وأصفر","برتقالي وأحمر"], answer: 1 },
      { q: "لأي منتخب يلعب ليونيل ميسي؟", options: ["البرازيل","أوروغواي","تشيلي","الأرجنتين"], answer: 3 },
      { q: "ماذا يعني 'هاتريك' في كرة القدم؟", options: ["3 أهداف من لاعب واحد","3 تمريرات حاسمة","3 بطاقات صفراء","3 تصديات"], answer: 0 },
      { q: "ما اسم الديربي بين ريال مدريد وبرشلونة؟", options: ["ديربي مدريد","الكلاسيكو","ديربي كتالونيا","لا مانيتا"], answer: 1 },
      { q: "أي منتخب فاز بأول كأس عالم عام 1930؟", options: ["البرازيل","الأرجنتين","أوروغواي","إيطاليا"], answer: 2 },
      { q: "كم لاعباً يمكن أن يجلس على دكة الاحتياط؟", options: ["5","7","9","11"], answer: 1 },
      { q: "أي نادٍ يلعب في ملعب أولد ترافورد؟", options: ["ليفربول","تشيلسي","مانشستر يونايتد","أرسنال"], answer: 2 },
      { q: "أي منتخب فاز بكأس العالم 2018؟", options: ["ألمانيا","كرواتيا","بلجيكا","فرنسا"], answer: 3 },
      { q: "كم دقيقة تستمر كل شوط؟", options: ["40","45","50","60"], answer: 1 },
      { q: "في أي مدينة يقع نادي برشلونة؟", options: ["مدريد","إشبيلية","برشلونة","فالنسيا"], answer: 2 },
      { q: "ما اللون التقليدي لقميص منتخب البرازيل؟", options: ["أخضر","أزرق","أصفر","أبيض"], answer: 2 },
      { q: "أي نادٍ لندني يُلقّب بـ'البلوز'؟", options: ["أرسنال","توتنهام","تشيلسي","وست هام"], answer: 2 },
      { q: "من فاز بكأس العالم 2014؟", options: ["البرازيل","الأرجنتين","ألمانيا","فرنسا"], answer: 2 },
      { q: "أي لاعب يُلقّب بـ'البرغوث'؟", options: ["نيمار","ميسي","رونالدو","مبابي"], answer: 1 },
      { q: "ماذا يعني البطاقة الحمراء في كرة القدم؟", options: ["إنذار","ركلة حرة","طرد اللاعب","ركلة جزاء"], answer: 2 },
      { q: "لأي منتخب يلعب نيمار؟", options: ["الأرجنتين","كولومبيا","البرازيل","البرتغال"], answer: 2 },
      { q: "أي نادٍ يُلقّب بـ'الريدز' في ليفربول؟", options: ["إيفرتون","ليفربول","مانشستر يونايتد","أرسنال"], answer: 1 },
      { q: "من فاز بيورو 2020 (الذي أُقيم في 2021)؟", options: ["إنجلترا","فرنسا","البرتغال","إيطاليا"], answer: 3 },
      { q: "ما عرض مرمى كرة القدم الرسمي؟", options: ["5.5 م","6 م","7.32 م","8 م"], answer: 2 },
      { q: "أي نادٍ يُلقّب بـ'المواطنون'؟", options: ["تشيلسي","أرسنال","مانشستر سيتي","توتنهام"], answer: 2 },
      { q: "في أي مدينة يقع ملعب باركس دي برانس؟", options: ["ليون","مارسيليا","باريس","بوردو"], answer: 2 },
      { q: "أي نادٍ فاز بدوري أبطال أوروبا 2022-23؟", options: ["ليفربول","بايرن","باريس","مانشستر سيتي"], answer: 3 },
      { q: "كم هدفاً سجل مبابي في مونديال 2022؟", options: ["6","7","8","9"], answer: 1 },
    ],
    medium: [
      { q: "أي نادٍ انضم إليه ميسي بعد برشلونة 2021؟", options: ["يوفنتوس","باريس سان جيرمان","مانشستر سيتي","بايرن"], answer: 1 },
      { q: "في أي عام تأسست FIFA؟", options: ["1900","1904","1910","1920"], answer: 1 },
      { q: "أي دولة استضافت كأس العالم 2018؟", options: ["البرازيل","ألمانيا","روسيا","فرنسا"], answer: 2 },
      { q: "من فاز بالكرة الذهبية 2023؟", options: ["مبابي","هالاند","ميسي","بنزيمة"], answer: 2 },
      { q: "أي نادٍ فاز بأكثر ألقاب دوري الأبطال؟", options: ["برشلونة","بايرن","ريال مدريد","ميلان"], answer: 2 },
      { q: "أقصى عدد تبديلات مسموح به في المباراة؟", options: ["3","4","5","6"], answer: 2 },
      { q: "من سجل هدف 'يد الله' 1986؟", options: ["بيليه","مارادونا","بلاتيني","لينيكر"], answer: 1 },
      { q: "أي نادٍ إنجليزي يُلقّب بـ'المدافعون'؟", options: ["تشيلسي","توتنهام","أرسنال","وست هام"], answer: 2 },
      { q: "من فاز بدوري أبطال أوروبا 2021-22؟", options: ["ليفربول","مانشستر سيتي","تشيلسي","ريال مدريد"], answer: 3 },
      { q: "في أي بلد وُلد كريستيانو رونالدو؟", options: ["إسبانيا","البرازيل","البرتغال","إيطاليا"], answer: 2 },
      { q: "أي نادٍ يُلقّب بـ'العجوز السيدة'؟", options: ["ميلان","إنتر","يوفنتوس","لاتسيو"], answer: 2 },
      { q: "كم مرة فازت فرنسا بكأس العالم؟", options: ["1","2","3","4"], answer: 1 },
      { q: "من هو الهداف التاريخي لريال مدريد؟", options: ["راؤول","بنزيمة","رونالدو","زيدان"], answer: 2 },
      { q: "ما اسم ملعب برشلونة؟", options: ["واندا متروبوليتانو","كامب نو","برنابيو","سان سيرو"], answer: 1 },
      { q: "أي منتخب أفريقي وصل لنصف نهائي مونديال 2022؟", options: ["نيجيريا","السنغال","المغرب","الكاميرون"], answer: 2 },
      { q: "من كان الهداف في مونديال 2018؟", options: ["ميسي","رونالدو","هاري كين","لوكاكو"], answer: 2 },
      { q: "أي نادٍ انضم إليه نيمار بعد برشلونة عام 2017؟", options: ["ريال مدريد","مانشستر سيتي","باريس سان جيرمان","بايرن"], answer: 2 },
      { q: "أي دولة فازت بكوبا أمريكا 2021؟", options: ["البرازيل","كولومبيا","أوروغواي","الأرجنتين"], answer: 3 },
      { q: "من فاز بالدوري الإنجليزي 2022-23؟", options: ["ليفربول","مانشستر سيتي","أرسنال","تشيلسي"], answer: 1 },
      { q: "أي نادٍ إيطالي يشارك إنتر في ملعب سان سيرو؟", options: ["يوفنتوس","لاتسيو","ميلان","روما"], answer: 2 },
      { q: "من يحمل رقم قياسي أهداف الدوري الإنجليزي؟", options: ["رووني","أندرو كول","آلان شيرر","لامبارد"], answer: 2 },
      { q: "ما جنسية روبرت ليفاندوفسكي؟", options: ["تشيكية","سلوفاكية","مجرية","بولندية"], answer: 3 },
      { q: "أي نادٍ حقق الثلاثية عام 1999 مع فيرغسون؟", options: ["أرسنال","تشيلسي","مانشستر يونايتد","ليفربول"], answer: 2 },
      { q: "من هو الأكثر مشاركة في تاريخ منتخب إنجلترا؟", options: ["بيكهام","رووني","جيرارد","شيلتون"], answer: 1 },
      { q: "أي نادٍ يلعب في ملعب أليانز أرينا؟", options: ["بوروسيا دورتموند","بايرن ميونخ","باير ليفركوزن","شالكه"], answer: 1 },
      { q: "أي دولة فازت ببطولة أمم أوروبا 2016؟", options: ["فرنسا","ألمانيا","ويلز","البرتغال"], answer: 3 },
      { q: "في أي عام سجل زيدان ضربة رأسه لماتيرازي؟", options: ["2002","2004","2006","2008"], answer: 2 },
      { q: "من فاز بجائزة أفضل لاعب في مونديال 2022؟", options: ["مبابي","مودريتش","ميسي","بنزيمة"], answer: 2 },
      { q: "أي نادٍ انضم إليه هالاند عام 2022؟", options: ["باريس","ريال مدريد","مانشستر سيتي","برشلونة"], answer: 2 },
      { q: "ما منتخب فيرجيل فان دايك؟", options: ["بلجيكا","الدنمارك","هولندا","ألمانيا"], answer: 2 },
      { q: "في أي عام فاز ليستر سيتي بالدوري الإنجليزي؟", options: ["2014","2015","2016","2017"], answer: 2 },
      { q: "أي نادٍ جنوب أمريكي يمتلك أكثر ألقاب كوبا ليبرتادوريس؟", options: ["بوكا جونيورز","ريفر بليت","سانتوس","إنديبندينتي"], answer: 3 },
      { q: "من سجل هدف الفوز في نهائي يورو 2016؟", options: ["رونالدو","ناني","إيدر","كواريزما"], answer: 2 },
    ],
    hard: [
      { q: "أي حارس يمتلك رقم قياسي لأكثر شباك نظيفة بالدوري الإنجليزي؟", options: ["شمايكل","سيمان","بيتر تشيك","فان دير سار"], answer: 2 },
      { q: "في أي عام فاز أياكس بآخر لقب له في دوري الأبطال؟", options: ["1992","1995","1997","1999"], answer: 1 },
      { q: "من سجل هدف الفوز لفرنسا في نهائي 1998؟", options: ["زيدان","هنري","بيتي","تريزيغيه"], answer: 0 },
      { q: "من فاز بأكثر جوائز كرة ذهبية حتى 2024؟", options: ["رونالدو","ميسي","رونالدينيو","بلاتيني"], answer: 1 },
      { q: "ما جنسية الحارس ليف ياشين؟", options: ["أوكرانية","ألمانية","سوفيتية/روسية","مجرية"], answer: 2 },
      { q: "أي نادٍ تركه زيدان للانضمام لريال مدريد؟", options: ["مارسيليا","موناكو","يوفنتوس","ليون"], answer: 2 },
      { q: "كم مرة فازت البرازيل بكأس العالم؟", options: ["4","5","6","3"], answer: 1 },
      { q: "من كان الهداف في كأس العالم 2014؟", options: ["ميسي","نيمار","مولر","جيمس"], answer: 2 },
      { q: "من يمتلك رقم قياسي في أهداف المنتخبات الدولية عام 2024؟", options: ["رونالدو","ميسي","علي دائي","مختار دهاري"], answer: 0 },
      { q: "في أي عام عُدّلت قاعدة التسلل بشكل جذري؟", options: ["1863","1883","1925","1950"], answer: 2 },
      { q: "من سجل أسرع هاتريك في تاريخ الدوري الإنجليزي؟", options: ["روبي فاولر","مايكل أوين","ساديو ماني","شيرر"], answer: 0 },
      { q: "أي نادٍ فاز بأكبر عدد من ألقاب الدوري الأرجنتيني؟", options: ["بوكا جونيورز","سان لورنزو","ريفر بليت","راسينج"], answer: 2 },
      { q: "أي دولة فازت بأول بطولة أمم أوروبا عام 1960؟", options: ["إسبانيا","إيطاليا","الاتحاد السوفيتي","يوغوسلافيا"], answer: 2 },
      { q: "لكم نادٍ لعب رونالدو (CR7) حتى 2024؟", options: ["4","5","6","7"], answer: 1 },
      { q: "ما لقب اللاعب روبرتو باجيو الشهير؟", options: ["الذهبي","ذيل الحصان الإلهي","السحر الإيطالي","الأسطورة"], answer: 1 },
      { q: "ما الاسم الحقيقي للاعب بيليه؟", options: ["إدواردو","إيدسون","إرنستو","إيفاريستو"], answer: 1 },
      { q: "أي نادٍ غادره رونالدو (R9) قبل ريال مدريد؟", options: ["أياكس","PSV","برشلونة","كروزيرو"], answer: 1 },
      { q: "من كان أول لاعب يفوز بكأس العالم 3 مرات؟", options: ["غارينشا","بيليه","ديدي","نيلتون سانتوس"], answer: 1 },
      { q: "أي نادٍ غادره هنري قبل الانضمام لأرسنال؟", options: ["موناكو","باريس","يوفنتوس","ليون"], answer: 0 },
      { q: "من يحمل رقم قياسي أكثر مباريات في دوري الأبطال؟", options: ["تشافي","كاسياس","كريستيانو رونالدو","راؤول"], answer: 2 },
      { q: "من سجل أكثر أهداف في موسم دوري إنجليزي واحد؟", options: ["شيرر","أندرو كول","محمد صلاح","إيرلينغ هالاند"], answer: 3 },
      { q: "في أي عام دخل الـVAR للدوري الإنجليزي؟", options: ["2017","2018","2019","2020"], answer: 2 },
      { q: "أي نادٍ انضم إليه سواريز بعد ليفربول؟", options: ["ريال مدريد","باريس","برشلونة","يوفنتوس"], answer: 2 },
      { q: "كم منتخباً أفريقياً وصل لنصف نهائي كأس العالم؟", options: ["0","1","2","3"], answer: 2 },
      { q: "من كان أول لاعب من خارج أوروبا وجنوب أمريكا يفوز بالكرة الذهبية؟", options: ["جورج ويا","إيتو","دروغبا","جاي جاي أوكوتشا"], answer: 0 },
      { q: "من هو الحكم الذي طرد زيدان في نهائي 2006؟", options: ["كولينا","هوراسيو إليزوندو","غراهام بول","هوارد ويب"], answer: 1 },
      { q: "أي نادٍ فاز بأول دوري أبطال أوروبا عام 1956؟", options: ["ميلان","برشلونة","ريال مدريد","يوفنتوس"], answer: 2 },
      { q: "ما كان نتيجة مباراة ألمانيا والبرازيل 2014 الشهيرة؟", options: ["6-0","7-1","5-0","8-2"], answer: 1 },
      { q: "من كان مدرب فرنسا في مونديال 1998؟", options: ["ديشامب","وينغر","إيمي جاكيه","روجيه ليمير"], answer: 2 },
      { q: "أي دولة استضافت كأس العالم أكثر من غيرها؟", options: ["البرازيل","ألمانيا","إيطاليا","المكسيك"], answer: 3 },
      { q: "ما المركز الذي اشتهر به فرانز بيكنباور؟", options: ["مهاجم","جناح","ليبيرو","حارس مرمى"], answer: 2 },
      { q: "من سجل الهدف الوحيد في نهائي كأس العالم 2010؟", options: ["دافيد فييا","تشافي","إنييستا","فيرناندو توريس"], answer: 2 },
      { q: "أي نادٍ فاز بأكبر عدد من ألقاب الليغا الإسبانية؟", options: ["برشلونة","أتليتيكو مدريد","فالنسيا","ريال مدريد"], answer: 3 },
      { q: "في أي عام فاز رونالدينيو بالكرة الذهبية؟", options: ["2003","2004","2005","2006"], answer: 2 },
    ]
  }
};
